version: '3'
services:
  vertx-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
        - vertx-network
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4GB
#    environment:
#      POSTGRES_HOST: postgres
#      POSTGRES_PORT: 5432
#      POSTGRES_DB: mydb
#      POSTGRES_USER: myuser
#      POSTGRES_PASSWORD: mypassword

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vertx
      POSTGRES_USER: vertx
      POSTGRES_PASSWORD: vertx
    networks:
        - vertx-network
networks:
  vertx-network:
